export const GENERICS_GET_REQUEST_CALL = 'GENERICS_GET_REQUEST_CALL';
export const GENERICS_POST_REQUEST_CALL = 'GENERICS_POST_REQUEST_CALL';
export const GENERICS_REQUEST_FAILED = 'GENERICS_REQUEST_FAILED';
export const GENERICS_REQUEST_SUCCESS = 'GENERICS_REQUEST_SUCCESS';